name: Deploy to staging
on:
  push:
    branch:
      - [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying the fronted to staging
    steps: 
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          echo "${{ secrets.DEV_SSH_SERVER }}"
          echo " doing ssh in dev server "
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} root@${{ secrets.DEV_SSH_SERVER }}
          echo "into dev server"


