name: Deploy to staging
on:
  push:
    branch:
      - [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying the fronted to staging
    steps: 
      - run: |
          echo " doing ssh in dev server "
          ssh -i {{secrets.SSH_PRIVATE_KEY}} root@{{secrets.DEV_SERVER}}
          echo "into dev server"


